### ISSUE TITLE
Convert Shepherd into an RTOS

### ISSUE THREAD

**Issue by Sabramz** [Northeastern-Electric-Racing/Shepherd-BMS#108]
### Description

Shepherd currently does everything in the main loop. We want Shepherd to run on an RTOS.

### Acceptance Criteria

- [ ] Test in acceleration
- [ ] Test in autocross / endurance
- [ ] Test charging

### Proposed Solution

- [ ] Stm32CubeMX codegen for RTOS
- [ ] Convert Shepherd's functions into tasks organized by logic/function, how often they should be run, and priority
- [ ] Rigorous testing

**Comment by dyldonahue** [comment]
@Sabramz no rush but lets try to fix this tik sometime before Fall like we talked about (only mentioning now since im beginning a repo run through)
